### PR TITLE
Add Roman to integer conversion code in Java

### PR DESCRIPTION
**Pull request by ShreyaPrabhu**
As per Issue #2 , Added java code for existing problem (Roman to Integer conversion)

### CODE REVIEW

**Comment by ShreyaPrabhu** [comment]
@somnathrakshit The PR is ready for review.

**Comment by somnathrakshit** [comment]
Thanks!

**Comment by ShreyaPrabhu** [comment]
@somnathrakshit I can see that this was marked as a repo for Hacktoberfest but on Hacktoberfest official website, this shows as PR created to ineligible repository. 

More info - 
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

Could you please add the topic?

**Comment by somnathrakshit** [comment]
Done.

**Pull request merged**
